services:
    reservations:
      build:
        context: .
        dockerfile: ./apps/reservations/Dockerfile
        target: development
      command: pnpm run start:dev reservations
      env_file:
        - ./apps/reservations/.env
      ports:
       - '3200:3200'
      volumes:
       - .:/usr/src/app

    auth:
      build:
        context: .
        dockerfile: ./apps/auth/Dockerfile
        target: development
      command: pnpm run start:dev auth
      env_file:
       - ./apps/auth/.env
      ports:
        - '3001:3001'
      volumes:
        - .:/usr/src/app

    payments:
      build:
        context: .
        dockerfile: ./apps/payments/Dockerfile
        target: development
      command: pnpm run start:dev payments
      env_file:
        - ./apps/payments/.env
      volumes:
        - .:/usr/src/app

    notifications:
      build:
        context: .
        dockerfile: ./apps/notifications/Dockerfile
        target: development
      command: pnpm run start:dev notifications
      env_file:
        - ./apps/notifications/.env
      volumes:
        - .:/usr/src/app

    permissions:
      build:
        context: .
        dockerfile: apps/permissions/Dockerfile
        target: development
      command: pnpm run start:dev permissions
      env_file:
        - apps/permissions/.env
      ports:
        - '3005:3005'
      volumes:
        - .:/usr/src/app

    roles:
      build:
        context: .
        dockerfile: apps/roles/Dockerfile
        target: development
      command: pnpm run start:dev roles
      env_file:
        - apps/roles/.env
      ports:
        - '3007:3007'
      volumes:
        - .:/usr/src/app

    mongo:
      image: mongo
      ports:
       - '27017:27017'
